### PR TITLE
Port to electron + add new features

### PR DESCRIPTION
**Pull request by blurymind**
Hi, this is somewhat of a big change pull, so please bear with me

It ports Yarn over to electron, while also adding a couple of new features:

- Ability to easily create links to other existing nodes via a new helper menu:
 
yarn-linkmaking
(addressing #34 )

- Ability to test dialogue via e new "Run" menu (using bondage.js and bbcode)
 
yarn-testerbbcode
(addressing #29 )

- file drag and drop (including support for dropping multiple files )
yarn-dropfile
(addressing #32 )

- Automatically create New Nodes from [[new]] and [[new|choice]] - if no nodes exist for them:
yarn-autonewnodefromchoice
(addressing https://github.com/InfiniteAmmoInc/Yarn/issues/27)

- Ability to run more than one instance of Yarn
(addressing #59 )

- Lots of fixes and new key bindings

I am not sure if the shift to electron would be welcome by the original creators:
@InfiniteAmmoInc , @seiyria and @beeglebug

Please let me know,so I know if a better route for me is to fork it to "Yarn-plus" or "Yarn-electron" or something

In order to try it just run
npm install
then
npm start

### CODE REVIEW

**Comment by blurymind** [comment]
@charblar hi thank you for looking into this. Sorry I forgot to mention that bondage.js doesnt support running the syntax 
`<<function(parameters)>>`
At the moment. I have submited another pull request to add that already here:
https://github.com/jhayley/bondage.js/pull/33
And used the same gif to demonstrate it there

The author of bondage.js @jhayley will review it when she has time, but basically adds the feature.
Feel free to run the test with it and see if it works :)

**Comment by charblar** [comment]
@blurymind hey, no problem! I assumed that was the case. I personally know Hayley and will work with her in the coming days to resolve that.

Thank you for the clarification, looking forward to your additional commits!

**Comment by blurymind** [comment]
@charblar thank you for looking into that. It wasn't really intended to be a part of this pull request - and still isnt. I needed the javascript parsing capability for my personal project. So in my pull request here that is not supported, it's more of a feature for bondage.js and not yarn.

On the front of this one - I fixed the previous styling problems and console errors, while also cleaning up the code.Now it should work much better :)

**Comment by blurymind** [comment]
Ok going back to bondage.js, my approach was not right, so I will create another pull request - possibly later in the week.
I misunderstood the intended design of <<>> and the problem, so scrapped it and will redo that to allow <<function(parameters)>> syntax without introducing a new node type

**Comment by blurymind** [comment]
A little update on this- after reading some requests here I decided to add the option to also show commands like this:
yarnrunnerupdate1
Also made the window self close when finished

**Comment by charblar** [comment]
Awesome, thanks for keeping us updated. Looking forward to it.

**Comment by blurymind** [comment]
Another update on this- I re-enabled all the file commands now- so the electron version is on-par with the main one.
Please note that the command debugging depends on a pull request I made to bondage.js - so command debugging is not there yet, since that needs to be merged first

I also made some changes to my vscode start script to get it to run it from a portable flash thumb- if you are trying it- you might have to revert the changes in .vscode/tasks.json for now :) 

Anyways, I hope to have an electron build ready for testing soon-ish

**Comment by jhayley** [comment]
As a note, the changes being made to bondage.js are largely unrelated to the electron change and i recommend separating these concerns. Those feature requests aren't needed to port yarn to electron

**Comment by blurymind** [comment]
@jhayley yes of course. I have been using the electron port for testing the pull I am doing to bondage.js

Just wanted to note that the electron port at the moment will have this feature broken for most

**Comment by blurymind** [comment]
A little update on this.
There is now an electron release- that removes the command debugging for now and uses the official bondage.js branch (@jhayley )
:) 
You can download it here
https://github.com/blurymind/Yarn/releases/tag/untagged-1933231011a749959b56

**Comment by blurymind** [comment]
A little update:

I added:
- file drag and drop (including support for dropping multiple files )
yarn-dropfile

dropping multiple files appends them:
yarn-dropfilesmany

- Support for deleting multiple selected nodes (via the delete key)
- Fix spacebar key (should be on key release- so it doesnt repeat while held)
- new key binding- ctrl+space while editing a node will switch to edit the next node
- new key binding- ctrl+enter while editing a node will save and close the node
- run document format prettify

**Comment by blurymind** [comment]
@charblar this is shaping up to be an epic release and I have addressed your request - it is no longer spitting out an error :) 

Can you tell me what else needs to be done to get this merged?

**Comment by julsam** [comment]
I really love the new features @blurymind +1 , but (and I don't want to sound like an ungrateful ***,) i wished you didn't run prettify... or at least not in the same commit as other changes.

**Comment by blurymind** [comment]
New build out - go grab a copy! :) 
https://github.com/blurymind/Yarn/releases/tag/untagged-4a6d4d2b95bf71bdd264

**Comment by charblar** [comment]
@blurymind Hey, I was out of country the past week and am taking a look at all of this now.  Thank you for you patience. 

For the remainder of this PR I request that we hold off on features and changes outside the scope of porting to Electron.

**Comment by blurymind** [comment]
@charblar Hi no problem. I will stop adding any new features and focus on the porting.

From my tests the electron port seems to work fine. Can you please test and review it :) I hope I haven't introduced any regressions

**Comment by charblar** [comment]
@blurymind Looks good to me, I would ask that you first ignore the .vscode directory first and remove the existing files from inside of it and then we can merge it in.

**Comment by blurymind** [comment]
> @blurymind Looks good to me, I would ask that you first ignore the .vscode directory first and remove the existing files from inside of it and then we can merge it in.

@charblar It is done now :) 
Thank you for reviewing the changes.

**Comment by julsam** [comment]
Just to add more feedback: I've been using a modified version of @blurymind 's electron port for the last 2 weeks, I have not encounter any problems so far, it's very stable.

I've been using it only on windows though (win7 x64).

**Comment by blurymind** [comment]
@julsam thank you for taking the time to test it. I noticed that you even merged my changes to your fork (https://github.com/julsam/VineEditor) which is flattering 😊 
After @charblar merges these changes I think of adding a few more small but useful things in a separate pull.

**Comment by blurymind** [comment]
@charblar  Thank you !! 🎉 😊 🎉 🍾

**Pull request merged**
