### PR TITLE
editor changed to ace

### PR DESCRIPTION
**Pull request by seiyria**
please test before merging and let me know what you think (you have far more practical usecases than I do after all!)

### CODE REVIEW

**Comment by InfiniteAmmoInc** [comment]
Highlighting works great! Thanks so much. :)

I wonder if enabling the menu will allow copy + paste + undo etc to work on mac now...

**Comment by seiyria** [comment]
It doesn't seem to work on my mac, so you may have to do what #3 did. It definitely works on Aces test site so I think the app is still swallowing those keybindings.

**Comment by InfiniteAmmoInc** [comment]
Yeah, enabling the menubar like lorne did seems to work. :D Awesome.

**Comment by InfiniteAmmoInc** [comment]
Thanks so much. :)

**Comment by seiyria** [comment]
Not a problem, I'm looking forward to more cool games from you!

**Pull request merged**
