### PR TITLE
added native os/x menu support for handling edit events

### PR DESCRIPTION
**Pull request by LorenBednar**
commented out things that were block key presses on lines 195-197
   + will need to confirm this doesn't break functionality on windows/linux.

### CODE REVIEW

**Comment by seiyria** [comment]
+1, this was going to be my second idea.

**Comment by AlecHolowka** [comment]
Problem with this is that Noel is doing a trick to get syntax highlighting to work. I think the trick is that the user is updating text in a hidden (normal) field and then the display field is updated with that text filtered through code to color it and setup the line numbers properly.

To make this work involves emulating some functions like copy, paste, cut, undo it seems

**Comment by seiyria** [comment]
If you guys need syntax highlighting, I'd recommend replacing your control with [ace](http://ace.c9.io/#nav=about) and making a custom highlighter (it's very easy to do). If you need help with replacing the component, I'd be willing to do that.

**Comment by AlecHolowka** [comment]
That sounds pretty awesome if you wouldn't mind doing it :0

**Comment by seiyria** [comment]
I opened #4 for discussion regarding that topic, so as not to have this thread be too off-topic.

**Comment by InfiniteAmmoInc** [comment]
Ended up using this to fix paste + stuff after seiyria implemented Ace. :) Thanks Loren!

**Pull request closed without merging**
