### PR TITLE
Decreased font size to fit more lines of text in editor

### PR DESCRIPTION
**Pull request by Subliminalman**
* Increased size of editor window slightly
* Decreased size of font to 0.9em

### CODE REVIEW

**Comment by desplesda** [comment]
Can you show a before/after screenshot of this?

**Comment by Subliminalman** [comment]
Sure thing!

Before:

screen shot 2017-09-28 at 7 11 08 pm


After:

screen shot 2017-09-28 at 7 12 21 pm

**Comment by desplesda** [comment]
Cool, looks good!

Note to self: consider adding controls for modifying stuff like font size, though that would require a preferences system...

**Comment by Subliminalman** [comment]
That's something that I want to look into (at least for adding controls to increase and decrease in editor)

**Pull request merged**
